# https://circleci.com/docs/2.0/configuration-reference

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:latest

jobs:
  build-and-test:
    <<: *defaults
    steps:
      - checkout
      - run: npm ci
      - run: npm run coverage
      - run: npm run coverage:upload
      - run: npm run coverage:check

workflows:
  version: 2
  build:
    jobs:
      - build-and-test